name: Docker Image CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - TEST_AGAINST: 3.25.4
            TESTSUITE_VERSION: 3.11.1
          - TEST_AGAINST: 3.15.0
            TESTSUITE_VERSION: 3.11.1
          - TEST_AGAINST: 3.11.7
            TESTSUITE_VERSION: 3.11.1

    steps:
    - uses: actions/checkout@v2

    - name: Create data directories
      run: |
        mkdir data
        sudo chown -R 1000:1000 ./testsuite ./data

    - name: Test if it builds
      run: docker build -t local-pocketmine-mp --build-arg PMMP_TAG=${{ matrix.TEST_AGAINST }} pocketmine-mp
    
    - name: Test if it runs the normal server properly
      run: echo stop | docker run --rm -i local-pocketmine-mp

    - name: Test if it loads plugins
      run: |
        echo stop | docker run --rm -i -v $PWD/data:/data -v $PWD/testsuite/${{ matrix.TESTSUITE_VERSION }}/create-data:/plugins local-pocketmine-mp
        test -f data/plugin_data/data-test/create-data
        "test \"$(cat data/plugin_data/data-test/create-data)\" == successful"

    - name: Test if it persists plugin data
      run: echo stop | docker run --rm -i -v $PWD/data:/data -v $PWD/testsuite/${{ matrix.TESTSUITE_VERSION }}/verify-data:/plugins local-pocketmine-mp
  
    - name: Test if it downloads plugins
      run: "test ${{ matrix.TEST_AGAINST }} '!=' master && echo stop | docker run --rm -i -v $PWD/data:/data -v $PWD/testsuite/${{ matrix.TESTSUITE_VERSION }}/verify-plugins:/plugins -e POCKETMINE_PLUGINS='PurePerms:1.4.2-c2a PureChat' local-pocketmine-mp"
